"""added profile pic

Revision ID: 363c5cd45406
Revises: 470218b49ba0
Create Date: 2023-12-18 01:32:42.647939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363c5cd45406'
down_revision = '470218b49ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
