"""about author added

Revision ID: 470218b49ba0
Revises: 2fdf49ed6926
Create Date: 2023-12-17 23:32:35.325165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470218b49ba0'
down_revision = '2fdf49ed6926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_author')
    # ### end Alembic commands ###
