"""added profile pic

Revision ID: 718b71fa38ac
Revises: 363c5cd45406
Create Date: 2023-12-18 01:39:40.171969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718b71fa38ac'
down_revision = '363c5cd45406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
